# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 677971bccbce7bb6ffcd02cd48c79cf7a379cfe92fb927bdd39b9b68a771375fa4346990fa2956cae71eb0516a25cda4d59b9cd3aacf01b4ee908f5a1a6d3b06

test:
  secret_key_base: bea260c4bdc7a51466c65bd02fd7fbdac15114c213dfa25c7d37f22a8fb30f3c4ddf58b1a5c0fb4fc860abbccbbc35cba6f87ce3a441ba0caa21b7120766c277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
